version: "3"  # optional since v1.27.0
services:
  php:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
  nginx:
    image: nginx:1.21.3
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/conf.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    depends_on:
      - php
  db:
    image: postgres:14.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password